---
# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: p-2022-091
  labels:
    type: p-2022-091
---
# create Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-python-client
  namespace: p-2022-091
  labels:
    app: deployment-python-client
spec:
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: python-client
  template:
    metadata:
      labels:
        app: python-client
    spec:
      # imagePullSecrets: # for pulling from private registry
      # - name: regcred
      containers:
        - name: python-client
          image: "urial1500/python-client:latest"
          # imagePullPolicy: IfNotPresent
          ports:
            - name: port-client
              containerPort: 8024
              protocol: TCP
          # resources:
          #   limits:
          #     cpu: 2000m
          #     memory: 2048Mi
          #   requests:
          #     cpu: 200m
          #     memory: 256Mi
          env:
            # denamic address
            - name: HOST_LOW_AREA
              value: "svc-python-area-low.p-2022-091.svc.cluster.local"
            - name: HOST_HIGH_AREA
              value: "svc-python-area-high.p-2022-091.svc.cluster.local"
            - name: HOST_ATTACKER
              value: "svc-python-area-attacker.p-2022-091.svc.cluster.local"
            - name: HOST_SERVER
              value: "svc-python-area-server.p-2022-091.svc.cluster.local"
            - name: PORT_LOW_AREA
              value: "8012"  # _port-area-low._tcp.svc-python-area-server.p-2022-091.svc.cluster.local
            - name: PORT_HIGH_AREA
              value: "8022"
            - name: PORT_ATTACKER
              value: "8014"
            - name: PORT_SERVER
              value: "8030"
          # readinessProbe:
          #   tcpSocket:
          #     port: port-client
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: port-client
          #   initialDelaySeconds: 14
          #   periodSeconds: 20
          # volumeMounts:
---
# create Service
apiVersion: v1
kind: Service
metadata:
  name: svc-python-client
  namespace: p-2022-091
spec:
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: ""
  ports:
    - name: port-client
      port: 8024
      targetPort: port-client
      protocol: TCP
  selector:
    app: python-client
---