name: Area_Low_CI

on:
  workflow_dispatch:
  push:
    branches: 
    - "master"
    paths:
    - "Area_Low/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repo.
      uses: actions/checkout@v3

    - name: Login to docker hub registry.
      run: |
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push "Area_Low".
    #   run: |
    #     IMAGE_TAG=$(date +%s)
    #     docker run --rm --privileged tonistiigi/binfmt --install all
    #     docker buildx create --use
    #     DOCKER_TARGET_PLATFORM="linux/arm64,linux/amd64"
    #     docker buildx build ./Area_Low --platform $DOCKER_TARGET_PLATFORM \
    #     --tag urial1500/python-area-low:$IMAGE_TAG --tag urial1500/python-area-low:latest  \
    #     --file ./Area_Low/Dockerfile \
    #     --output type=image,push=true

    - name: Deploy to k8s cluster.
      env:
        # cat /mnt/c/bgu/p-2022-091/DOC/simulation/kubecofig-p-2022-091 | base64
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        mkdir -p $HOME/.kube/
        echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
        kubectl apply -f yml/area-low.yml
        kubectl -n p-2022-091 patch deployment "deployment-python-area-low" -p \
        "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"