name: Area_High_CI

on:
  push:
    branches: 
    - "master"
    paths:
    - "Area_High/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repo.
      uses: actions/checkout@v3

    - name: Login to docker hub registry.
      run: |
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push "Area_High".
      run: |
        IMAGE_TAG=$(date +%s)
        docker run --rm --privileged tonistiigi/binfmt --install all
        docker buildx create --use
        DOCKER_TARGET_PLATFORM="linux/arm64,linux/amd64"
        docker buildx build ./Area_High --platform $DOCKER_TARGET_PLATFORM \
        --tag urial1500/python-area-high:$IMAGE_TAG --tag urial1500/python-area-high:latest  \
        --file ./Area_High/Dockerfile \
        --output type=image,push=true

    - name: Deploy to k8s cluster.
      env:
        # cat /mnt/c/bgu/p-2022-091/DOC/simulation/kubecofig-p-2022-091 | base64
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        mkdir -p $HOME/.kube/
        echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
        kubectl apply -f yml/area-high.yml