name: Area_Low_CI

on:
  push:
    branches: 
    - "master"
    paths:
    - "Area_Low/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:      
      DOCKER_TARGET_PLATFORM: linux/arm/v7   

    steps:
    - name: Check the repo.
      uses: actions/checkout@v3

    - name: Login to docker hub registry.
      run: |
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push "Area_Low".
      run: |
        IMAGE_TAG=$(date +%s)
        docker build ./Area_Low --file ./Area_Low/Dockerfile --tag urial1500/python-area-low:$IMAGE_TAG --tag urial1500/python-area-low:latest
        docker push urial1500/python-area-low:$IMAGE_TAG
        docker push urial1500/python-area-low:latest


    - name: Build and push "Area_Low".
      uses: pguyot/arm-runner-action@v2
      with:
        commands: |
          IMAGE_TAG=$(date +%s)
          docker build ./Area_Low --file ./Area_Low/Dockerfile --tag urial1500/python-area-low:$IMAGE_TAG --tag urial1500/python-area-low:latest
          docker push urial1500/python-area-low:$IMAGE_TAG
          docker push urial1500/python-area-low:latest

    # - name: Deploy to k8s cluster.
    #   uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     # args: apply -f yml/container-python-Client.yaml
    #     args: get nodes