name: Attacker_CI

on:
  push:
    branches: 
    - "master"
    paths:
    - "Attacker/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check the repo
      uses: actions/checkout@v3

    - name: login to docker hub registry 
      run: |
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push "Attacker"
      run: |
        IMAGE_TAG=$(date +%s)
        docker build ./Attacker --file ./Attacker/Dockerfile --tag urial1500/python-attacker:$IMAGE_TAG
        docker push urial1500/python-attacker:$IMAGE_TAG
