name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check the repo
      uses: actions/checkout@v3

    - name: login to docker hub registry 
      env:
        CR_PAT: ${{ secrets.CR_DOCKER }}
      run: |
        docker login docker.io -u MY_USERNAME --password-stdin MY_PASSWORD
        # docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
        docker build ./Area_Low --file ./Area_Low/Dockerfile --tag python-area-low:$(date +%s)
        docker tag python-area-low:$(date +%s) urial1500/python-area-low:latest
        docker push urial1500/python-area-low:latest
