name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check the repo
      uses: actions/checkout@v3

    - name: login to docker hub registry 
      run: |
        IMAGE_TAG=$(date +%s)
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build ./Area_Low --file ./Area_Low/Dockerfile --tag python-area-low:$IMAGE_TAG
        docker tag python-area-low:$IMAGE_TAG urial1500/python-area-low:latest
        docker push urial1500/python-area-low:latest
