name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check the repo
      uses: actions/checkout@v3

    - name: login to docker hub registry 
#               echo $CR_PAT | docker login docker.io -u MY_USERNAME --password-stdin
      run: docker login docker.io -u urial1500 --password-stdin z9f48jHE36hs#$f4db
      env:
        CR_PAT: ${{ secrets.CR_DOCKER }}


    - name: Build the Docker image "Area_Low"
      run: |
        docker build ./Area_Low --file ./Area_Low/Dockerfile --tag python-area-low:$(date +%s)
        docker tag python-area-low:$(date +%s) urial1500/python-area-low:latest
        docker push urial1500/python-area-low:latest

#       with:
#         image: nanajanashia/demo-app
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         tags: v1, latest
#         dockerfile: ./Area_Low/Dockerfile.ci


