name: Satellite_CI

on:
  push:
    branches: 
    - "master"
    paths:
    - "Satellite/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repo.
      uses: actions/checkout@v3

    - name: Login to docker hub registry.
      run: |
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push "Satellite".
      run: |
        IMAGE_TAG=$(date +%s)
        docker build ./Satellite --file ./Satellite/Dockerfile --tag urial1500/python-satellite:$IMAGE_TAG
        docker push urial1500/python-satellite:$IMAGE_TAG

    - name: Deploy to k8s cluster.
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f ./yml/container-python-Satellite.yaml
